-- MySQL Script generated by MySQL Workbench
-- Thu Dec 16 19:42:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Publisher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Publisher` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Publisher` (
  `idPublisher` INT NOT NULL,
  `PubName` VARCHAR(45) NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPublisher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Book` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `ISBN` VARCHAR(17) NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  `NofPages` INT NOT NULL,
  `Publisher_idPublisher` INT NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_Book_Publisher1_idx` (`Publisher_idPublisher` ASC) VISIBLE,
  CONSTRAINT `fk_Book_Publisher1`
    FOREIGN KEY (`Publisher_idPublisher`)
    REFERENCES `mydb`.`Publisher` (`idPublisher`)
	ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Author` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Author` (
  `idAuthor` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Gender` VARCHAR(1) NOT NULL,
  `Birthdate` DATE NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  CHECK( `Gender` IN ('F','M')),
  PRIMARY KEY (`idAuthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`People`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`People` ;

CREATE TABLE IF NOT EXISTS `mydb`.`People` (
  `idPeople` INT NOT NULL,
  `PeopName` VARCHAR(45) NOT NULL,
  `PeopSurname` VARCHAR(45) NOT NULL,
  `PeopBirthDate` DATE NOT NULL,
  PRIMARY KEY (`idPeople`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PeopleRead`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PeopleRead` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PeopleRead` (
  `Year` YEAR NOT NULL,
  `People_idPeople` INT NOT NULL,
  `Book_ISBN` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`People_idPeople`, `Book_ISBN`),
  INDEX `fk_PeopleRead_People_idx` (`People_idPeople` ASC) VISIBLE,
  INDEX `fk_PeopleRead_Book1_idx` (`Book_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_PeopleRead_People`
    FOREIGN KEY (`People_idPeople`)
    REFERENCES `mydb`.`People` (`idPeople`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PeopleRead_Book1`
    FOREIGN KEY (`Book_ISBN`)
    REFERENCES `mydb`.`Book` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AuthorWrite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AuthorWrite` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AuthorWrite` (
  `Author_idAuthor` INT NOT NULL,
  `Book_ISBN` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`Author_idAuthor`, `Book_ISBN`),
  INDEX `fk_AuthorWrite_Author1_idx` (`Author_idAuthor` ASC) VISIBLE,
  INDEX `fk_AuthorWrite_Book1_idx` (`Book_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_AuthorWrite_Author1`
    FOREIGN KEY (`Author_idAuthor`)
    REFERENCES `mydb`.`Author` (`idAuthor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AuthorWrite_Book1`
    FOREIGN KEY (`Book_ISBN`)
    REFERENCES `mydb`.`Book` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
